// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/demo.proto

package violet.video.common.proto_gen.demo;

public interface DemoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DemoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string param = 1;</code>
   */
  java.lang.String getParam();
  /**
   * <code>string param = 1;</code>
   */
  com.google.protobuf.ByteString
      getParamBytes();
}
