// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/demo.proto

package violet.video.common.proto_gen.demo;

public interface DemoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DemoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
